artifact_uri: /Users/camdouglas/quark/mlruns/505953476862620945/c8bef425e9ad4146bdc3dd8ebdc50fcd/artifacts
end_time: 1755834676500
entry_point_name: ''
experiment_id: '505953476862620945'
lifecycle_stage: active
run_id: c8bef425e9ad4146bdc3dd8ebdc50fcd
run_name: thalamus_sensory_relay
source_name: ''
source_type: 4
source_version: ''
start_time: 1755834676026
status: 3
tags: []
user_id: camdouglas
