line-length = 100
target-version = "py311"

[lint]
select = ["E","F","W"]
ignore = []

exclude = [
  "data",
  "docs",
  "backups",
  "venv",
  ".venv",
  "repo_indexes",
]

[format]
quote-style = "preserve"
indent-style = "space"


