# 🚀 AWS DEPLOYMENT CONFIGURATION FOR ULTRA-FAST PHYSICS SIMULATION
# Optimized for maximum speed and cost efficiency

# EC2 INSTANCE CONFIGURATIONS
ec2_instances:
  # 🧠 TRAINING INSTANCES (Multi-GPU)
  training:
    p4d_24xlarge:  # 8x A100 40GB - Best for large model training
      instance_type: "p4d.24xlarge"
      gpu_count: 8
      gpu_type: "A100"
      memory_gb: 400
      vcpus: 96
      storage: "nvme"
      cost_per_hour: 32.77
      use_case: "Large model training, distributed training"
      
    p3_16xlarge:  # 8x V100 16GB - Cost-effective training
      instance_type: "p3.16xlarge"
      gpu_count: 8
      gpu_type: "V100"
      memory_gb: 488
      vcpus: 64
      storage: "ssd"
      cost_per_hour: 24.48
      use_case: "Medium model training, cost optimization"
      
    g5_48xlarge:  # 8x A10G 24GB - Balanced performance/cost
      instance_type: "g5.48xlarge"
      gpu_count: 8
      gpu_type: "A10G"
      memory_gb: 384
      vcpus: 192
      storage: "ssd"
      cost_per_hour: 16.24
      use_case: "Inference, fine-tuning, cost-effective training"

  # ⚡ INFERENCE INSTANCES (Single/Multi-GPU)
  inference:
    g5_2xlarge:  # 1x A10G 24GB - Single GPU inference
      instance_type: "g5.2xlarge"
      gpu_count: 1
      gpu_type: "A10G"
      memory_gb: 96
      vcpus: 8
      storage: "ssd"
      cost_per_hour: 1.212
      use_case: "Single model inference, development"
      
    g5_12xlarge:  # 4x A10G 24GB - Multi-GPU inference
      instance_type: "g5.12xlarge"
      gpu_count: 4
      gpu_type: "A10G"
      memory_gb: 384
      vcpus: 48
      storage: "ssd"
      cost_per_hour: 4.096
      use_case: "Multi-model inference, load balancing"

# 🚀 AUTO SCALING CONFIGURATION
auto_scaling:
  min_capacity: 1
  max_capacity: 10
  target_cpu_utilization: 70
  target_memory_utilization: 80
  scale_up_cooldown: 300  # 5 minutes
  scale_down_cooldown: 600  # 10 minutes

# 💾 STORAGE OPTIMIZATION
storage:
  # EBS Optimized Volumes
  ebs_optimized: true
  volume_types:
    gp3:  # General Purpose SSD
      iops: 16000
      throughput: 1000
      cost_per_gb_month: 0.08
    io2:  # Provisioned IOPS SSD
      iops: 64000
      throughput: 1000
      cost_per_gb_month: 0.125
      
  # S3 Storage Classes
  s3_storage_classes:
    standard:  # Hot data
      cost_per_gb_month: 0.023
      access_time: "milliseconds"
    intelligent_tiering:  # Automatic optimization
      cost_per_gb_month: 0.0125
      access_time: "milliseconds to hours"
    glacier_instant_retrieval:  # Cold data
      cost_per_gb_month: 0.004
      access_time: "milliseconds"

# 🌐 NETWORK OPTIMIZATION
networking:
  # VPC Configuration
  vpc:
    cidr_block: "10.0.0.0/16"
    subnets:
      - availability_zone: "us-east-1a"
        cidr: "10.0.1.0/24"
        type: "public"
      - availability_zone: "us-east-1b"
        cidr: "10.0.2.0/24"
        type: "private"
        
  # Load Balancer
  load_balancer:
    type: "application"
    scheme: "internet-facing"
    idle_timeout: 60
    connection_draining_timeout: 300
    
  # CloudFront CDN
  cloudfront:
    enabled: true
    price_class: "PriceClass_100"  # US, Canada, Europe
    cache_policy: "Managed-CachingOptimized"

# 🔧 CONTAINER OPTIMIZATION
container:
  # ECS/EKS Configuration
  platform_version: "LATEST"
  cpu_architecture: "x86_64"  # or "arm64" for Graviton
  memory_reservation: 4096
  port_mappings:
    - container_port: 8000
      protocol: "tcp"
      
  # Docker Image Optimization
  base_image: "nvidia/cuda:12.4-devel-ubuntu22.04"
  multi_stage_build: true
  layer_caching: true
  image_compression: true

# 📊 MONITORING & LOGGING
monitoring:
  # CloudWatch
  cloudwatch:
    metrics_interval: 60  # seconds
    log_retention_days: 30
    alarms:
      cpu_utilization:
        threshold: 80
        period: 300
      memory_utilization:
        threshold: 85
        period: 300
      gpu_utilization:
        threshold: 90
        period: 300
        
  # X-Ray Tracing
  xray:
    enabled: true
    sampling_rate: 0.1
    
  # Application Performance Monitoring
  apm:
    datadog: false
    new_relic: false
    custom_metrics: true

# 🎯 COST OPTIMIZATION
cost_optimization:
  # Spot Instances
  spot_instances:
    enabled: true
    max_price: "on-demand"
    interruption_behavior: "terminate"
    
  # Reserved Instances
  reserved_instances:
    term: "1_year"
    payment_option: "all_upfront"
    savings: 0.40  # 40% savings
    
  # Savings Plans
  savings_plans:
    type: "compute"
    commitment: "1_year"
    hourly_commitment: 10
    savings: 0.66  # 66% savings
    
  # Cost Alerts
  cost_alerts:
    monthly_budget: 1000
    alert_threshold: 0.8  # 80% of budget

# 🚀 PERFORMANCE OPTIMIZATION
performance:
  # Kernel Tuning
  kernel_parameters:
    vm.swappiness: 1
    vm.dirty_ratio: 15
    vm.dirty_background_ratio: 5
    
  # GPU Optimization
  gpu_optimization:
    cuda_malloc_async: true
    cuda_graphs: true
    mixed_precision: true
    tensor_cores: true
    
  # Memory Optimization
  memory_optimization:
    huge_pages: true
    transparent_huge_pages: "madvise"
    swappiness: 1
    
  # Network Optimization
  network_optimization:
    tcp_congestion_control: "bbr"
    tcp_window_scaling: true
    tcp_timestamps: true

# 🔒 SECURITY CONFIGURATION
security:
  # IAM Roles
  iam_roles:
    - name: "EC2Role"
      policies:
        - "AmazonS3ReadOnlyAccess"
        - "CloudWatchLogsFullAccess"
        - "EC2InstanceConnect"
        
  # Security Groups
  security_groups:
    - name: "PhysicsSimulationSG"
      rules:
        - protocol: "tcp"
          port: 22
          source: "0.0.0.0/0"
        - protocol: "tcp"
          port: 8000
          source: "0.0.0.0/0"
        - protocol: "tcp"
          port: 443
          source: "0.0.0.0/0"
          
  # Encryption
  encryption:
    ebs_encryption: true
    s3_encryption: true
    transit_encryption: true
