daily_budget: 100.0
max_concurrent_jobs: 10
platforms:
- cost_per_hour: 0.05
  credentials_path: ~/.aws/credentials
  instance_types:
  - t3.medium
  - t3.large
  - c5.large
  max_instances: 5
  name: aws_ec2
  provider: aws
  regions:
  - us-east-1
  - us-west-2
  - eu-west-1
- cost_per_hour: 0.06
  credentials_path: ~/.config/gcloud/application_default_credentials.json
  instance_types:
  - n1-standard-2
  - n1-standard-4
  - n1-highmem-2
  max_instances: 5
  name: gcp_compute
  provider: gcp
  regions:
  - us-central1
  - europe-west1
  - asia-east1
- cost_per_hour: 0.07
  credentials_path: ~/.azure/credentials
  instance_types:
  - Standard_B2s
  - Standard_B4ms
  - Standard_D2s_v3
  max_instances: 5
  name: azure_vm
  provider: azure
  regions:
  - eastus
  - westus2
  - westeurope
