# connectome/maintenance_config.yaml
# Configuration for the connectome maintenance agent

maintenance:
  intervals:
    optimization_seconds: 300      # 5 minutes
    cleanup_seconds: 1800         # 30 minutes
    health_check_seconds: 30      # 30 seconds
    
  connection_optimization:
    enable_pruning: true
    prune_threshold: 0.05         # Remove connections below 5% strength
    max_prune_percentage: 25      # Never remove more than 25% of weak connections
    enable_redundancy_removal: true
    max_redundant_percentage: 10  # Process max 10% of triangles
    enable_small_world_optimization: true
    target_clustering: 0.15
    triangle_closing_count: 10
    
  directory_cleanup:
    enable_temp_cleanup: true
    enable_log_rotation: true
    max_log_size_mb: 10
    enable_export_archiving: true
    archive_after_days: 7
    enable_directory_organization: true
    
  system_health:
    enable_adaptive_intervals: true
    stress_multiplier: 1.2        # Slow down maintenance when stressed
    healthy_multiplier: 0.9       # Speed up maintenance when healthy
    max_exports_size_mb: 100      # Trigger cleanup if exports exceed this
    
  required_connections:
    # These module connections should never be pruned
    preserve_links:
      - ["PFC", "THA"]    # Prefrontal-Thalamic
      - ["PFC", "BG"]     # Prefrontal-Basal Ganglia  
      - ["BG", "THA"]     # Basal Ganglia-Thalamic
      - ["THA", "WM"]     # Thalamic-Working Memory
      - ["PFC", "WM"]     # Prefrontal-Working Memory
      - ["PFC", "DMN"]    # Prefrontal-Default Mode
      - ["PFC", "HIP"]    # Prefrontal-Hippocampal
      - ["DMN", "HIP"]    # Default Mode-Hippocampal
      - ["PFC", "ATT"]    # Prefrontal-Attention
      - ["THA", "ATT"]    # Thalamic-Attention
      - ["ARCH", "PFC"]   # Architecture-Prefrontal
      - ["ARCH", "THA"]   # Architecture-Thalamic
      - ["ARCH", "ATT"]   # Architecture-Attention

logging:
  level: INFO
  format: "[%(asctime)s] %(levelname)s: %(message)s"
  save_to_file: true
  log_file: "connectome/logs/maintenance.log"
  
reporting:
  enable_statistics: true
  stats_file: "connectome/exports/maintenance_stats.json"
  enable_periodic_reports: true
  report_interval_hours: 24
  report_file: "connectome/exports/maintenance_report.json"
