#!/usr/bin/env python3
"""Regenerate management/rules/roadmaps/ROADMAPS_INDEX.md.
Run this script whenever roadmap docs change.

Integration: Not simulator-integrated; repository tooling for indexing, validation, or CI.
Rationale: Executed by developers/CI to maintain repo health; not part of runtime simulator loop.
"""
import sys
from pathlib import Path
from filelock import FileLock, Timeout

def _generate() -> None:
    root = Path(__file__).resolve().parents[2] / "management" / "rules" / "roadmaps"
    index_file = root / "ROADMAPS_INDEX.md"
    rows = []
    for fp in root.rglob('*'):
        if fp.suffix.lower() not in {'.md', '.yaml', '.yml'} or fp.name == 'ROADMAPS_INDEX.md':
            continue
        title = None; status='—'
        with fp.open(encoding='utf-8', errors='ignore') as f:
            for ln in f:
                if not title and ln.lstrip().startswith('#'):
                    title = ln.lstrip('#').strip()
                if 'Current Status' in ln or 'Integration Status' in ln or 'Integration status' in ln:
                    status = ln.split(':')[-1].strip()
                    break
        rows.append((title or fp.stem.replace('_',' ').title(), fp.relative_to(root).as_posix(), status))
    rows.sort(key=lambda x: x[0].lower())
    header = '# 🗺️ Quark Roadmaps – Comprehensive Index\n\n'
    header += 'Auto-generated by tools_utilities/scripts/generate_roadmap_index.py.\n\n'
    table = '| # | Title | Relative Path | Status |\n| 0 | --- | --- | --- |\n'
    for i,(t,p,s) in enumerate(rows,1):
        table += f'| {i} | {t} | {p} | {s} |\n'
    index_file.write_text(header+table, encoding='utf-8')
    print(f'ROADMAPS_INDEX.md updated with {len(rows)} entries')


def main() -> None:
    lock_path = Path(__file__).with_suffix('.lock')
    try:
        with FileLock(lock_path, timeout=2):
            _generate()
    except Timeout:
        print("[generate_roadmap_index] Another process holds the lock – skipping regeneration.", file=sys.stderr)

if __name__ == '__main__':
    main()
