name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest mlflow
      - name: Run tests
        run: |
          pytest -q || pytest -q --maxfail=1
      - name: Smoke MLflow log
        run: |
          python - <<'PY'
          import mlflow
          mlflow.set_tracking_uri('file:./mlruns')
          mlflow.set_experiment('CI')
          with mlflow.start_run(run_name='ci_smoke'):
              mlflow.log_param('ci', 'true')
              mlflow.log_metric('ok', 1.0)
          print('mlflow ok')
          PY
