name: Auto-Update README from Quark State

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (if present)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate README
        run: |
          python utilities/generate_readme.py

      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain README.md)" ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add README.md
            git commit -m "docs(readme): auto-update from Quark State"
            git push
          else
            echo "No README changes to commit."
          fi


