name: Rules Validation

on:
  push:
    branches: [ main, dev, '**' ]
  pull_request:
    branches: [ main, dev, '**' ]

jobs:
  validate-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run validation gate
        run: |
          make validate-ci
