name: streaming-tests

on:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - 'tests/resource_manager/**'
      - 'requirements-ci.txt'
      - '.github/workflows/streaming-tests.yml'
  workflow_dispatch:

jobs:
  streaming:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
          pip install -e .
      - name: Run streaming unit tests
        run: pytest -q tests/resource_manager/test_cli_integration.py tests/resource_manager/test_streaming.py
