name: streaming-tests

on:
  # Temporarily disabled due to dependency issues in CI
  # pull_request:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  streaming:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run streaming unit tests
        run: pytest -q tests/resource_manager/test_cli_integration.py tests/resource_manager/test_streaming.py
